version: "3"
services:
    php:
        build: docker/
        volumes:
            - ./code:/usr/share/code
        tty: true
        environment:
            DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
            TEST_DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db_test:3306/${MYSQL_DATABASE}
        ports:
            - 8888:8888
    db:
        image: mariadb:10.2
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 33066:3306
    db_test:
        image: mariadb:10.2
        volumes:
        - "./.data/db_test:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
        - 33065:3306